worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is-testing: false

server-port: 8080

dbconnection: 'postgresql://userver-postgresql-template_user:password@localhost:5432/userver-postgresql-template_db_1'

config-fallback-path: @CONFIG_FALLBACK_PATH@
